routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\GoogleController;
use App\Http\Controllers\FacultyController;
use App\Http\Controllers\MajorController;
use App\Http\Controllers\NewsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('major', MajorController::class);

Route::resource('news', NewsController::class);

Route::resource('faculty', FacultyController::class);

Route::get('auth/google', [GoogleController::class, 'redirectToGoogle'])->name('google.login');
Route::get('auth/google/callback', [GoogleController::class, 'handleGoogleCallback']);

app/Models/Major.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Major extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function faculty(){
        return $this->belongsTo(Faculty::class);
    }
}

app/Http/Controllers/MajorController.php
<?php

namespace App\Http\Controllers;

use App\Models\Faculty;
use App\Models\Major;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class MajorController extends Controller
{

    public function __construct()
    {
        $this->middleware(['auth','admin'])->except([
            'index'
        ]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $majors = Major::orderBy('created_at', 'ASC')->get();
        return view('major.index',compact('majors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $faculties = Faculty::all();
        return view('major.create', compact('faculties'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $validated = $request->validate([
        //     $request->name => ['required','string','unique:majors'],
        //     $request->description => ['required','string'],
        // ]);

        $major = Major::create([
            'name' => $request->name,
            'description' => $request->description,
            'faculty_id' => $request->faculty,
            'website' => $request->website,
        ]);

        return redirect(route('major.index'))->with('status','Major berhasil dibuat');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Major  $major
     * @return \Illuminate\Http\Response
     */
    public function show(Major $major)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Major  $major
     * @return \Illuminate\Http\Response
     */
    public function edit(Major $major)
    {
        $faculties = Faculty::all();
        return view('major.edit',compact(['major','faculties']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Major  $major
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Major $major)
    {
        // $validated = $request->validate([
        //     $request->name => ['required','string'],
        //     $request->description => ['required','string'],
        // ]);
        
        Major::where('id',$major->id)->update([
            'name' => $request->name,
            'description' => $request->description
        ]);

        return redirect(route('major.index'))->with('status','Major berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Major  $major
     * @return \Illuminate\Http\Response
     */
    public function destroy(Major $major)
    {
        Major::destroy($major->id);
        return redirect(route('major.index'))->with('status','Major berhasil dihapus');
    }
}

resources/views/major/create.blade.php
@extends('layouts.app')
@section('content')
<div class="row justify-content-center">
    <div class="col-md-10">
        <div class="card">
            <div class="card-header text-uppercase font-weight-bold">
                Create Major
            </div>
            <div class="card-body">
                <form action="{{ route('major.store') }}" method="post">
                    <div class="form-group row">
                        <label for="faculty" class="col-md-4 col-form-label text-md-right">Faculty</label>
                        <div class="col-md-6">
                            <select name="faculty" id="faculty" class="form-control" required>
                                @foreach ($faculties as $faculty)
                                    <option value="{{ $faculty->id }}">{{ $faculty->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        @csrf
                        <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>
                        <div class="col-md-6">
                            <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus required>
                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="description" class="col-md-4 col-form-label text-md-right">Description</label>
                        <div class="col-md-6">
                            <textarea name="description" id="description" class="form-control  @error('description') is-invalid @enderror" autocomplete="description" required></textarea>
                                @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        @csrf
                        <label for="website" class="col-md-4 col-form-label text-md-right">Website</label>
                        <div class="col-md-6">
                            <input id="website" type="text" class="form-control @error('website') is-invalid @enderror" name="website" value="{{ old('website') }}" required autocomplete="website" autofocus required>
                                @error('website')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-6 offset-4">
                            <button type="submit" class="btn btn-primary font-weight-bold text-uppercase">
                                <i class="fa fa-plus">

                                </i>
                                Create
                            </button>
                        </div>                        
                    </div>
                </form>
            </div>
        </div>  
    </div>
</div>    
@endsection

resources/views/major/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="row justify-content-center">
    <div class="col-md-10">
        <div class="card">
            <div class="card-header text-uppercase font-weight-bold">
                Update Major
            </div>
            <div class="card-body">
                <form action="{{ route('major.update',['major'=>$major]) }}" method="post">
                    <div class="form-group row">
                        <label for="faculty" class="col-md-4 col-form-label text-md-right">Faculty</label>
                        <div class="col-md-6">
                            <select name="faculty" id="faculty" class="form-control">
                                @foreach ($faculties as $faculty)
                                    <option value="{{ $faculty->id }}" {{ ($faculty->id == $major->faculty->id) ? 'selected' : '' }}>{{ $faculty->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        @csrf
                        @method('put')
                        <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>
                        <div class="col-md-6">
                            <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $major->name }}" required autocomplete="name" autofocus required>
                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="description" class="col-md-4 col-form-label text-md-right">Description</label>
                        <div class="col-md-6">
                            <textarea name="description" id="description" class="form-control  @error('description') is-invalid @enderror" autocomplete="description" required>{{ $major->description }}</textarea>                            
                                @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        @csrf
                        <label for="website" class="col-md-4 col-form-label text-md-right">Website</label>
                        <div class="col-md-6">
                            <input id="website" type="text" class="form-control @error('website') is-invalid @enderror" name="website" value="{{ $major->website}}" required autocomplete="website" autofocus required>
                                @error('website')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-6 offset-4">
                            <button type="submit" class="btn btn-info font-weight-bold text-uppercase">
                                <i class="fa fa-pen">

                                </i>
                                Update
                            </button>
                        </div>                        
                    </div>
                </form>
            </div>
        </div>  
    </div>
</div>    
@endsection

resources/views/major/index.blade.php
@extends('layouts.app')
@section('content')
    @if (session('status'))
        <div class="alert alert-success" role="alert">
            {{ session('status') }}
        </div>
    @endif
    <div class="row">
        <div class="col">
            <h2 class="font-weight-bold text-uppercase">
                MAJORS
            </h2>
        </div>
        @auth
            @if (auth()->user()->level == 'admin')
                <div class="col">
                    <a href="{{ route('major.create') }}" class="btn btn-success float-right text-uppercase font-weight-bold">
                        <i class="fa fa-plus mr-2"></i> Create</a>
                </div>
            @endif
        @endauth
    </div>
    <hr>
    <div class="row">
        <div class="col">
            <table class="table" id="major_table">
                <thead>
                    <tr>
                        <th>Major Name</th>
                        <th>Faculty</th>
                        <th>Description</th>
                        <th>Website</th>
                        <th>Action</th>
                    </tr>
                </thead>            
                <tbody>
                    @foreach ($majors as $major)
                    <tr>
                        <td>{{ $major->name }}</td>
                        <td>{{ $major->faculty->name }}</td>
                        <td>{{ $major->description }}</td>
                        <td> <a href=" {{ $major->website }}" class="btn-link"> {{ $major->website }}</a></td>
                        <td>
                            @auth
                                @if (auth()->user()->level == 'admin')
                                    <a href="{{ route('major.edit', ['major' => $major]) }}"
                                        class="btn btn-info text-white font-weight-bold text-uppercase">
                                        <i class="fa fa-edit"></i>
                                        Edit
                                    </a>
                                    <form action="{{ route('major.destroy', ['major' => $major]) }}" method="post"
                                        class="form-inline float-left">
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="btn btn-danger text-uppercase font-weight-bold mr-3"
                                            onclick="return confirm('are u sure?')">
                                            <i class="fa fa-trash">
    
                                            </i>
                                            Delete
                                        </button>
                                    </form>
                                @else
                                    Not Permitted
                                @endif
                            @endauth
                            @guest
                                Not Permitted
                            @endguest
                        </td>
                    </tr>
                @endforeach
                </tbody>            
            </table>
        </div>        
    </div>
@endsection
@section('script')
    <script>
        $(function() {            
            $('#major_table').DataTable();
        });
    </script>
@endsection