routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\GoogleController;
use App\Http\Controllers\FacultyController;
use App\Http\Controllers\MajorController;
use App\Http\Controllers\NewsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('major', MajorController::class);

Route::resource('news', NewsController::class);

Route::resource('faculty', FacultyController::class);

Route::get('auth/google', [GoogleController::class, 'redirectToGoogle'])->name('google.login');
Route::get('auth/google/callback', [GoogleController::class, 'handleGoogleCallback']);

app/Models/Faculty.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Faculty extends Model
{
    use HasFactory;

    protected $guarded =[];

    public function majors(){
        return $this->hasMany(Major::class);
    }
}

app/Http/Controllers/FacultyController.php
<?php

namespace App\Http\Controllers;

use App\Models\Faculty;
use Illuminate\Http\Request;

class FacultyController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth','admin'])->except([
            'index','show'
        ]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $faculties = Faculty::all();
        return view('faculty.index',compact('faculties'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('faculty.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $faculty = Faculty::create([
            'name' => $request->name,
            'description' => $request->description,            
            'website' => $request->website,            
        ]);
        return redirect(route('faculty.index'))->with('status','Faculty berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Faculty  $faculty
     * @return \Illuminate\Http\Response
     */
    public function show(Faculty $faculty)
    {
        return view('faculty.show',compact('faculty'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Faculty  $faculty
     * @return \Illuminate\Http\Response
     */
    public function edit(Faculty $faculty)
    {
        return view('faculty.edit',compact('faculty'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Faculty  $faculty
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Faculty $faculty)
    {
        Faculty::where('id',$faculty->id)->update([
            'name' => $request->name,
            'description' => $request->description,            
            'website' => $request->website,            
        ]);

        return redirect(route('faculty.index'))->with('status','Faculty berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Faculty  $faculty
     * @return \Illuminate\Http\Response
     */
    public function destroy(Faculty $faculty)
    {
        Faculty::destroy($faculty->id);
        return redirect(route('faculty.index'))->with('status','Faculty berhasil dihapus');
    }
}

resources/views/faculty/create.blade.php
@extends('layouts.app')
@section('content')
<div class="row justify-content-center">
    <div class="col-md-10">
        <div class="card">
            <div class="card-header text-uppercase font-weight-bold">
                Create Faculty
            </div>
            <div class="card-body">
                <form action="{{ route('faculty.store') }}" method="post">                    
                    <div class="form-group row">
                        @csrf
                        <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>
                        <div class="col-md-6">
                            <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus required>
                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="description" class="col-md-4 col-form-label text-md-right">Description</label>
                        <div class="col-md-6">
                            <textarea name="description" id="description" class="form-control  @error('description') is-invalid @enderror" autocomplete="description" required></textarea>
                                @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        @csrf
                        <label for="website" class="col-md-4 col-form-label text-md-right">Website</label>
                        <div class="col-md-6">
                            <input id="website" type="text" class="form-control @error('website') is-invalid @enderror" name="website" value="{{ old('website') }}" required autocomplete="website" autofocus required>
                                @error('website')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                        </div>
                    </div>                    
                    <div class="form-group row">
                        <div class="col-md-6 offset-4">
                            <button type="submit" class="btn btn-primary font-weight-bold text-uppercase">
                                <i class="fa fa-plus">

                                </i>
                                Create
                            </button>
                        </div>                        
                    </div>
                </form>
            </div>
        </div>  
    </div>
</div>    
@endsection

resources/views/faculty/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="row justify-content-center">
    <div class="col-md-10">
        <div class="card">
            <div class="card-header text-uppercase font-weight-bold">
                Edit Faculty
            </div>
            <div class="card-body">
                <form action="{{ route('faculty.update',['faculty'=>$faculty]) }}" method="post">                    
                    <div class="form-group row">
                        @csrf
                        @method('put')
                        <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>
                        <div class="col-md-6">
                            <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $faculty->name }}" required autocomplete="name" autofocus required>
                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="description" class="col-md-4 col-form-label text-md-right">Description</label>
                        <div class="col-md-6">
                            <textarea name="description" id="description" class="form-control  @error('description') is-invalid @enderror" autocomplete="description" required>{{ $faculty->description }}</textarea>
                                @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        @csrf
                        <label for="website" class="col-md-4 col-form-label text-md-right">Website</label>
                        <div class="col-md-6">
                            <input id="website" type="text" class="form-control @error('website') is-invalid @enderror" name="website" value="{{ $faculty->website }}" required autocomplete="website" autofocus required>
                                @error('website')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                        </div>
                    </div>                         
                    <div class="form-group row">
                        <div class="col-md-6 offset-4">
                            <button type="submit" class="btn btn-info font-weight-bold text-uppercase">
                                <i class="fa fa-pen">

                                </i>
                                Update
                            </button>
                        </div>                        
                    </div>
                </form>
            </div>
        </div>  
    </div>
</div>    
@endsection

resources/views/faculty/index.blade.php
@extends('layouts.app')
@section('content')
    @if (session('status'))
        <div class="alert alert-success" role="alert">
            {{ session('status') }}
        </div>
    @endif
    <div class="row">
        <div class="col">
            <h2 class="font-weight-bold text-uppercase">
                Faculties
            </h2>
        </div>
        @auth
            @if (auth()->user()->level == 'admin')
                <div class="col">
                    <a href="{{ route('faculty.create') }}" class="btn btn-success float-right text-uppercase font-weight-bold">
                        <i class="fa fa-plus mr-2"></i> Create</a>
                </div>
            @endif
        @endauth
    </div>
    <hr>
    <div class="row">
        <div class="col">
            <table class="table" id="faculty_table">
                <thead>
                    <tr>
                        <th>Faculty Name</th>                        
                        <th>Description</th>
                        <th>Website</th>
                        <th>Action</th>
                    </tr>
                </thead>            
                <tbody>
                    @foreach ($faculties as $faculty)
                    <tr>
                        <td>{{ $faculty->name }}</td>                        
                        <td>{{ $faculty->description }}</td>
                        <td> <a href=" {{ $faculty->website }}" class="btn btn-link"> {{ $faculty->website }}</a></td>
                        <td>
                            @auth
                                @if (auth()->user()->level == 'admin')
                                    <a href="{{ route('faculty.edit', ['faculty' => $faculty]) }}"
                                        class="btn btn-info text-white font-weight-bold text-uppercase">
                                        <i class="fa fa-edit"></i>
                                        Edit
                                    </a>
                                    <a href="{{ route('faculty.show',['faculty'=>$faculty]) }}"
                                        class="btn btn-warning font-weight-bold text-uppercase ml-2">
                                        <i class="fa fa-info"></i>
                                        Info
                                    </a>
                                    <form action="{{ route('faculty.destroy', ['faculty' => $faculty]) }}" method="post"
                                        class="form-inline float-left">
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="btn btn-danger text-uppercase font-weight-bold mr-3"
                                            onclick="return confirm('are u sure?')">
                                            <i class="fa fa-trash">
    
                                            </i>
                                            Delete
                                        </button>
                                    </form>
                                @else
                                    Not Permitted
                                @endif
                            @endauth
                            @guest
                                Not Permitted
                            @endguest
                        </td>
                    </tr>
                @endforeach
                </tbody>            
            </table>
        </div>        
    </div>
@endsection
@section('script')
    <script>
        $(function() {            
            $('#faculty_table').DataTable();
        });
    </script>
@endsection

resources/views/faculty/show.blade.php
@extends('layouts.app')
@section('content')
    @if (session('status'))
        <div class="alert alert-success" role="alert">
            {{ session('status') }}
        </div>
    @endif
    <div class="row">
        <div class="col">
            <h2 class="font-weight-bold text-uppercase">
                Faculty {{ $faculty->name }}
            </h2>
        </div>        
    </div>
    <div class="row">
        <div class="col">
            <div class="text-justify">
                {{ $faculty->description }}
            </div>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col">
            <table class="table" id="major_table">
                <thead>
                    <tr>
                        <th>Major Name</th>
                        <th>Faculty</th>
                        <th>Description</th>
                        <th>Website</th>
                        <th>Action</th>
                    </tr>
                </thead>            
                <tbody>
                    @foreach ($faculty->majors as $major)
                    <tr>
                        <td>{{ $major->name }}</td>
                        <td>{{ $major->faculty->name }}</td>
                        <td>{{ $major->description }}</td>
                        <td> <a href=" {{ $major->website }}" class="btn btn-link"> {{ $major->website }}</a></td>
                        <td>
                            @auth
                                @if (auth()->user()->level == 'admin')
                                    <a href="{{ route('major.edit', ['major' => $major]) }}"
                                        class="btn btn-info text-white font-weight-bold">
                                        <i class="fa fa-edit"></i>
                                        Edit
                                    </a>
                                    <form action="{{ route('major.destroy', ['major' => $major]) }}" method="post"
                                        class="form-inline float-left">
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="btn btn-danger text-uppercase font-weight-bold mr-3"
                                            onclick="return confirm('are u sure?')">
                                            <i class="fa fa-trash">
    
                                            </i>
                                            Delete
                                        </button>
                                    </form>
                                @else
                                    Not Permitted
                                @endif
                            @endauth
                            @guest
                                Not Permitted
                            @endguest
                        </td>
                    </tr>
                @endforeach
                </tbody>            
            </table>
        </div>        
    </div>
@endsection
@section('script')
    <script>
        $(function() {            
            $('#major_table').DataTable();
        });
    </script>
@endsection