routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\GoogleController;
use App\Http\Controllers\FacultyController;
use App\Http\Controllers\MajorController;
use App\Http\Controllers\NewsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('major', MajorController::class);

Route::resource('news', NewsController::class);

Route::resource('faculty', FacultyController::class);

Route::get('auth/google', [GoogleController::class, 'redirectToGoogle'])->name('google.login');
Route::get('auth/google/callback', [GoogleController::class, 'handleGoogleCallback']);

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function user(){
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\Models\News;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class NewsController extends Controller
{

    public function __construct()
    {
        $this->middleware(['auth','admin'])->except([
            'index','show'
        ]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $news = News::orderBy('created_at','ASC')->get();
        return view('news.index',compact('news'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('news.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $news = News::create([
            'title' => $request->title,
            'content' => $request->content,
            'user_id' => Auth::user()->id,

        ]);
        if ($request->hasFile('image')) {
            $filenameWithExt = $request->file('image')->getClientOriginalName ();
            // Get Filename
            $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);
            // Get just Extension
            $extension = $request->file('image')->getClientOriginalExtension();
            // Filename To store
            $fileNameToStore = $filename. '_'. time().'.'.$extension;
            //Upload Image
            $path = $request->file('image')->storeAs('public/image', $fileNameToStore);

            $news->image = $fileNameToStore;
            $news->save();
            }

        return redirect(route('news.index'))->with('status','News berhasil dibuat');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\News  $news
     * @return \Illuminate\Http\Response
     */
    public function show(News $news)
    {
        return view('news.show',compact('news'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\News  $news
     * @return \Illuminate\Http\Response
     */
    public function edit(News $news)
    {
        return view('news.edit',compact('news'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\News  $news
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, News $news)
    {
        News::where('id',$news->id)->update([
            'title' => $request->title,
            'content' => $request->content,
        ]);

        return redirect(route('news.index'))->with('status','News berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\News  $news
     * @return \Illuminate\Http\Response
     */
    public function destroy(News $news)
    {
        News::destroy($news->id);
        return redirect(route('news.index'))->with('status','News berhasil dihapus');
    }
}

resources/views/news/create.blade.php
@extends('layouts.app')
@section('content')
<div class="row justify-content-center">
    <div class="col-md-10">
        <div class="card">
            <div class="card-header text-uppercase font-weight-bold">
                Create News
            </div>
            <div class="card-body">
                <form action="{{ route('news.store') }}" method="post" enctype="multipart/form-data">
                    <div class="form-group row">
                        @csrf
                        <label for="title" class="col-md-4 col-form-label text-md-right">Title</label>
                        <div class="col-md-6">
                            <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') }}" required autocomplete="title" autofocus required>
                                @error('title')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="content" class="col-md-4 col-form-label text-md-right">Content</label>
                        <div class="col-md-6">
                            <textarea name="content" id="content" class="form-control  @error('content') is-invalid @enderror" autocomplete="content" required></textarea>
                                @error('content')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="" class="col-md-4 col-form-label text-md-right">Image</label>
                        <div class="col-md-6">
                            <input type="file" name="image" id="image" class="form-control-file">
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-6 offset-4">
                            <button type="submit" class="btn btn-primary">
                                <i class="fa fa-plus">

                                </i>
                                Create
                            </button>
                        </div>                        
                    </div>
                </form>
            </div>
        </div>  
    </div>
</div>    
@endsection

resources/views/news/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="row justify-content-center">
    <div class="col-md-10">
        <div class="card">
            <div class="card-header text-uppercase font-weight-bold">
                Edit News
            </div>
            <div class="card-body">
                <form action="{{ route('news.update',['news' => $news]) }}" method="post">
                    <div class="form-group row">
                        @csrf
                        @method('put')
                        <label for="title" class="col-md-4 col-form-label text-md-right">Title</label>
                        <div class="col-md-6">
                            <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ $news->title }}" required autocomplete="title" autofocus required>
                                @error('title')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="content" class="col-md-4 col-form-label text-md-right">Content</label>
                        <div class="col-md-6">
                            <textarea name="content" id="content" class="form-control  @error('content') is-invalid @enderror" autocomplete="content" required>{{ $news->content }}</textarea>
                                @error('content')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-6 offset-4">
                            <button type="submit" class="btn btn-info text-uppercase font-weight-bold">
                                <i class="fa fa-pen">

                                </i>
                                Update
                            </button>
                        </div>                        
                    </div>
                </form>
            </div>
        </div>  
    </div>
</div>    
@endsection

resources/views/news/index.blade.php
@extends('layouts.app')
@section('content')
    @if (session('status'))
        <div class="alert alert-success" role="alert">
            {{ session('status') }}
        </div>
    @endif
    <div class="row">
        <div class="col">
            <h2 class="font-weight-bold text-uppercase">
                NEWS
            </h2>
        </div>
        @auth
            @if (auth()->user()->level == 'admin')
                <div class="col">
                    <a href="{{ route('news.create') }}" class="btn btn-success float-right text-uppercase font-weight-bold">
                        <i class="fa fa-plus mr-2"></i> Create</a>
                </div>
            @endif
        @endauth
    </div>
    <hr>
    @foreach ($news as $n)
        <div class="card shadow mb-4">
            <div class="card-header text-uppercase font-weight-bold">
                <div class="row">
                    <div class="col">
                        {{ $n->title }}
                    </div>
                    @auth
                        @if (auth()->user()->level == 'admin')
                            <div class="col">
                                <a href="{{ route('news.edit', ['news' => $n]) }}"
                                    class="btn btn-info float-right text-white font-weight-bold">
                                    <i class="fa fa-edit"></i>
                                    Edit
                                </a>
                                <form action="{{ route('news.destroy', ['news' => $n]) }}" method="post"
                                    class="form-inline float-right">
                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="btn btn-danger text-uppercase font-weight-bold mr-3"
                                        onclick="return confirm('are u sure?')">
                                        <i class="fa fa-trash">

                                        </i>
                                        Delete
                                    </button>
                                </form>
                            </div>
                        @endif
                    @endauth
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-3">
                        <img class="img-thumbnail" src="{{ asset('storage/image/'.$n->image) }}" alt="{{ $n->image }}">
                    </div>
                    <div class="col">
                        {{ \Illuminate\Support\Str::limit($n->content, 500, '...') }}
                        <a href="{{ route('news.show',['news'=>$n]) }}" class="card-link"> Read More</a>
                    </div>
                </div>                
            </div>
            <div class="card-footer">
                This article posted at
                <div class="text-black-50">
                    {{ $n->created_at }}
                </div>
            </div>
        </div>
    @endforeach
@endsection

resources/views/news/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="card">
        <div class="card-header font-weight-bold text-uppercase">
            <div class="row">
                <div class="col">
                    {{ $news->title }}
                </div>
                <div class="col">
                    <div class="text-right">
                        Posted By: {{ $news->user->name }}
                    </div>
                </div>
            </div>            
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col">
                    <img class="img-fluid" src="{{ asset('storage/image/'.$news->image) }}" alt="{{ $news->image }}">
                </div>
            </div>
            <div class="row mt-4">
                <div class="col">
                    <div class="text-justify">
                        {{ $news->content }}
                    </div>                    
                </div>
            </div>            
        </div>
        <div class="card-footer">
            This article posted at
            <div class="text-black-50">
                {{ $news->created_at }}
            </div>
        </div>
    </div>
@endsection